part of 'wisperbot_config.dart';

/// Strongly-typed visitor location and browsing metadata.
///
/// Fields supplied here are mapped to standard `webchat_*` custom fields
/// with full IDE auto-completion and compile-time type safety.
@immutable
class WisperBotLocation {
  /// Creates strongly-typed visitor location metadata.
  const WisperBotLocation({
    this.country,
    this.countryCode,
    this.city,
    this.region,
    this.latitude,
    this.longitude,
    this.pageTitle,
    this.pageUrl,
  });

  /// Visitor country name (e.g. 'Bangladesh').
  final String? country;

  /// ISO 2-letter country code (e.g. 'BD', 'US'). Used for flag emoji.
  final String? countryCode;

  /// Visitor city name (e.g. 'Dhaka').
  final String? city;

  /// Visitor region/state name (e.g. 'Dhaka Division').
  final String? region;

  /// GPS Latitude coordinate (e.g. 23.8103).
  final double? latitude;

  /// GPS Longitude coordinate (e.g. 90.4125).
  final double? longitude;

  /// Current page or screen title (e.g. 'Telzen - eSIM for Everyone').
  final String? pageTitle;

  /// Current page URL or app screen deep-link (e.g. 'https://telzen.net/pricing').
  final String? pageUrl;

  /// Converts this location object into standard wire payload map.
  Map<String, dynamic> toMap() => <String, dynamic>{
        if (country != null) 'webchat_country': country,
        if (countryCode != null) 'webchat_country_code': countryCode,
        if (city != null) 'webchat_city': city,
        if (region != null) 'webchat_region': region,
        if (latitude != null) 'webchat_lat': latitude,
        if (longitude != null) 'webchat_lon': longitude,
        if (pageTitle != null) 'webchat_page_title': pageTitle,
        if (pageUrl != null) 'webchat_page_url': pageUrl,
      };

  @override
  String toString() =>
      'WisperBotLocation(country: $country, countryCode: $countryCode, city: $city, region: $region, '
      'latitude: $latitude, longitude: $longitude, pageTitle: $pageTitle, pageUrl: $pageUrl)';
}

/// Optional visitor profile supplied when a session starts.
///
/// [signature] must be generated by the integrating company's server. The
/// package deliberately redacts every field from [toString].
@immutable
class WisperBotUser {
  /// Creates an optional visitor profile.
  const WisperBotUser({
    this.externalId,
    this.name,
    this.email,
    this.avatarUrl,
    this.signature,
    this.location,
    this.customFields,
  });

  /// Stable host-application identifier for the visitor.
  final String? externalId;

  /// Visitor display name.
  final String? name;

  /// Visitor email address.
  final String? email;

  /// Visitor avatar URL.
  final Uri? avatarUrl;

  /// Server-generated HMAC identity signature.
  final String? signature;

  /// Strongly-typed visitor location and browsing metadata.
  final WisperBotLocation? location;

  /// Optional custom metadata and additional fields.
  final Map<String, dynamic>? customFields;

  /// Resolves merged custom fields including structured location fields.
  Map<String, dynamic>? get resolvedCustomFields {
    final locMap = location?.toMap();
    if (locMap == null || locMap.isEmpty) {
      return customFields;
    }
    return <String, dynamic>{
      ...locMap,
      if (customFields != null) ...customFields!,
    };
  }

  @override
  String toString() => 'WisperBotUser(externalId: [redacted], name: [redacted], '
      'email: [redacted], avatarUrl: [redacted], signature: [redacted], '
      'location: [redacted], customFields: [redacted])';
}
