library;

import 'package:flutter/material.dart';

import '../domain/contracts/media_adapter.dart';
import '../domain/contracts/session_store.dart';
import '../domain/errors/wisperbot_exception.dart';
import '../domain/events/chat_event.dart';

part '../diagnostics/diagnostic_event.dart';
part 'polling_config.dart';
part 'presentation_config.dart';
part 'theme_data.dart';
part 'user.dart';

/// Immutable options used to create a WisperBot client or prebuilt chat UI.
///
/// The [widgetKey] is a public routing identifier. It is not a secret. Identity
/// signatures must be generated by the integrating application's server and
/// supplied through [user].
@immutable
class WisperBotConfig {
  /// Creates package configuration for one WisperBot widget.
  const WisperBotConfig({
    required this.widgetKey,
    this.apiBaseUrl = 'https://wisperbot.com',
    this.user,
    this.theme,
    this.useApiColors = true,
    this.lightStatusBarIcons = false,
    this.presentation = WisperBotPresentation.fullScreen,
    this.enableTyping = true,
    this.mediaAdapter,
    this.polling = const WisperBotPollingConfig(),
    this.diagnostics,
    this.oneSignalAppId,
    this.enableOneSignal = true,
    this.requireNotificationPermission = false,
    this.sessionStore,
  });

  /// Public widget routing key issued by WisperBot.
  final String widgetKey;

  /// API origin used for widget requests.
  final String apiBaseUrl;

  /// Optional visitor profile and server-generated verified identity.
  final WisperBotUser? user;

  /// Host presentation overrides for the prebuilt UI.
  final WisperBotThemeData? theme;

  /// Whether server-provided colors participate in theme resolution.
  final bool useApiColors;

  /// Whether full-screen chat uses light (white) status-bar icons and text.
  ///
  /// Enable this for dark or strongly colored chat headers. This setting does
  /// not affect bottom-sheet or dialog presentations.
  final bool lightStatusBarIcons;

  /// Default presentation used by [WisperBotChat.open].
  final WisperBotPresentation presentation;

  /// Whether the controller may publish throttled visitor typing updates.
  final bool enableTyping;

  /// Optional override for built-in image/document picking and audio recording.
  /// When omitted, the prebuilt composer uses the SDK's default media adapter.
  final WisperBotMediaAdapter? mediaAdapter;

  /// Foreground polling intervals.
  final WisperBotPollingConfig polling;

  /// Optional receiver for redacted operational diagnostics.
  final WisperBotDiagnosticsCallback? diagnostics;

  /// Optional OneSignal App ID used for push notifications.
  final String? oneSignalAppId;

  /// Whether OneSignal push notification device registration is enabled.
  final bool enableOneSignal;

  /// Requires notification permission before chat starts. Requires OneSignal
  /// to be enabled with an app ID on Android or iOS.
  final bool requireNotificationPermission;

  /// Optional custom session credential store.
  final WisperBotSessionStore? sessionStore;
}
