library;

import 'package:flutter/material.dart';

import '../domain/contracts/media_adapter.dart';
import '../domain/errors/wisperbot_exception.dart';
import '../domain/events/chat_event.dart';

part '../diagnostics/diagnostic_event.dart';
part 'polling_config.dart';
part 'presentation_config.dart';
part 'theme_data.dart';
part 'user.dart';

/// Immutable options used to create a WisperBot client or prebuilt chat UI.
///
/// The [widgetKey] is a public routing identifier. It is not a secret. Identity
/// signatures must be generated by the integrating application's server and
/// supplied through [user].
@immutable
class WisperBotConfig {
  /// Creates package configuration for one WisperBot widget.
  const WisperBotConfig({
    required this.widgetKey,
    this.apiBaseUrl = 'https://wisperbot.com',
    this.user,
    this.theme,
    this.useApiColors = true,
    this.presentation = WisperBotPresentation.fullScreen,
    this.enableTyping = true,
    this.mediaAdapter,
    this.polling = const WisperBotPollingConfig(),
    this.diagnostics,
  });

  /// Public widget routing key issued by WisperBot.
  final String widgetKey;

  /// API origin used for widget requests.
  final String apiBaseUrl;

  /// Optional visitor profile and server-generated verified identity.
  final WisperBotUser? user;

  /// Host presentation overrides for the prebuilt UI.
  final WisperBotThemeData? theme;

  /// Whether server-provided colors participate in theme resolution.
  final bool useApiColors;

  /// Default presentation used by [WisperBotChat.open].
  final WisperBotPresentation presentation;

  /// Whether the controller may publish throttled visitor typing updates.
  final bool enableTyping;

  /// Optional host bridge for image selection and audio recording.
  final WisperBotMediaAdapter? mediaAdapter;

  /// Foreground polling intervals.
  final WisperBotPollingConfig polling;

  /// Optional receiver for redacted operational diagnostics.
  final WisperBotDiagnosticsCallback? diagnostics;
}
