name: wisperbot_chat
description: A customizable Flutter SDK for adding WisperBot customer chat to mobile, web, and desktop apps.
publish_to: none
version: 0.1.0-dev.1

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  flutter_svg: ^2.1.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
