import 'package:flutter/foundation.dart';

/// Optional visitor identity and profile supplied to a WisperBot runtime.
///
/// [signature] must be generated by the integrating company's server. The
/// package deliberately redacts every field from [toString].
@immutable
class WisperBotUser {
  /// Creates an optional visitor identity and profile.
  const WisperBotUser({
    this.externalId,
    this.name,
    this.email,
    this.avatarUrl,
    this.signature,
    this.customFields,
  });

  /// Stable host-application identifier for the visitor.
  final String? externalId;

  /// Visitor display name.
  final String? name;

  /// Visitor email address.
  final String? email;

  /// Visitor avatar URL.
  final Uri? avatarUrl;

  /// Server-generated HMAC identity signature.
  final String? signature;

  /// Optional custom metadata and additional fields.
  final Map<String, dynamic>? customFields;

  @override
  String toString() =>
      'WisperBotUser(externalId: [redacted], name: [redacted], '
      'email: [redacted], avatarUrl: [redacted], signature: [redacted], '
      'customFields: [redacted])';
}
